### 9.2 panic函数

error返回的时一般性错误，panic函数返回的是让程序崩溃的错误。

也就是当遇到不可恢复的错误状态的时候，如数据访问越界、空指针引用等，这些运行时错误会引起panic异常。

在一般情况下，我们不应通过panic函数来报告普通错误，而是应该只把它作为报告致命错误的一种方式。

当某些不应该发生的场景发生时，我们就应该调用panic。

一般而言，当panic异常发生时，程序会中断运行。随后，程序崩溃并输出日志信息。日志信息包括panic value和函数调用的堆栈跟踪信息。

当然，如直接用内置的panic函数也会引发panic异常；panic函数接受任何值作为参数。

下面给大家演示一下，直接调用panic函数，是否导致程序的崩溃。

```go
package main

import "fmt"

func TestA() {
    fmt.Println("func TestA()")
}

func TestB() {
    panic("panic: func TestB()")
}

func TestC() {
    fmt.Println("func TestC()")
}

func main() {
    TestA()
    TestB()
    TestC()
}
```

输出结果：

```bash
func TestA()
panic: panic: func TestB()

goroutine 1 [running]:
main.TestB(...)
        /Users/Anonymous/go/src/panic/panic_demo.go:10
main.main()
        /Users/Anonymous/go/src/panic/panic_demo.go:19 +0x96

Process finished with exit code 2
```

所以，我们在实际开发的过程中并不会直接调用panic\(\)函数，但是我们当程序遇到致命错误时候，系统会自动调用该函数来终止整个程序的运行，也就是系统内置了panic\(\)函数。

```go
package main

import "fmt"

func TestA() {
    fmt.Println("func TestA()")
}

func TestB(i int) {
    //panic("panic: func TestB()")
    var arr [10]int
    arr[i] = 1 // 数组越界
}

func TestC() {
    fmt.Println("func TestC()")
}

func main() {
    TestA()
    TestB(100)
    TestC()
}
```

输出结果：

```
func TestA()
panic: runtime error: index out of range [100] with length 10

goroutine 1 [running]:
main.TestB(...)
        /Users/Anonymous/go/src/panic/panic_demo.go:12
main.main()
        /Users/Anonymous/go/src/panic/panic_demo.go:21 +0x85

Process finished with exit code 2
```

通过观察错误信息，发现的确是panic异常，导致了整个程序崩溃。

总结：

可以认为 panic 和 recover 与其他语言中的 try-catch-finally 语句类似，只不过一般我们很少使用 panic 和 recover。而当我们使用了 panic 和 recover 时，也会比 try-catch-finally 更加优雅，代码更加整洁。



**需要注意的是，你应该尽可能地使用**[**错误**](https://studygolang.com/articles/12724)**，而不是使用 panic 和 recover。只有当程序不能继续运行的时候，才应该使用 panic 和 recover 机制**。

panic 有两个合理的用例。

1. **发生了一个不能恢复的错误，此时程序不能继续运行**。 一个例子就是 web 服务器无法绑定所要求的端口。在这种情况下，就应该使用 panic，因为如果不能绑定端口，啥也做不了。

2. **发生了一个编程上的错误**。 假如我们有一个接收指针参数的方法，而其他人使用`nil`作为参数调用了它。在这种情况下，我们可以使用 panic，因为这是一个编程错误：用`nil`参数调用了一个只能接收合法指针的方法。



