### 9.4 recover函数

运行时panic异常一旦被引发就会导致程序崩溃。这当然不是我们愿意看到的，因为谁也不能保证程序不会发生任何运行时错误。

Go语言为我们提供了专用于“拦截”运行时panic的内建函数——recover。它可以是当前的程序从运行时panic的状态中恢复并重新获得流程控制权。

* **注意：recover只有在defer调用的函数中有效。**

示例如下：

```go
package main

import "fmt"

func testA() {
	fmt.Println("testA")
}

func testB(x int) {
	//设置recover()

	//在defer调用的函数中使用recover()
	defer func() {
		//防止程序崩溃
		recover()
	}() //匿名函数

	var a [3]int
	a[x] = 999
}

func testC() {
	fmt.Println("testC")
}

func main() {
	testA()
	testB(3) //发生异常 中断程序
	testC()
}

// output:
// testA
// testC
```



